version: "3.8"
services:
  web:
    build: ./app
    image: 475803405878.dkr.ecr.us-east-2.amazonaws.com/calc_django_docker_aws:web_service
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
      - static_files:/app/calc_app/static/calc_app/
    expose:
      - 8000

  nginx:
    build: ./nginx
    image: 475803405878.dkr.ecr.us-east-2.amazonaws.com/calc_django_docker_aws:nginx_service
    volumes:
      - static_files:/home/app/staticfiles 
                                            #this creates a shareable volume between the web and nginx service. e.g share files between containers
    ports:
      - 80:80
      ##- 8000:80 for development 
    depends_on:
      - web   #makes sure that nginx runs and is created after the above web service
volumes:
  static_files:                     #creates the link between containers to share files between containers


